/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-local-store-workspace.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer-element.d.ts" />

declare namespace LogicElements {

  /**
   * `arc-local-store-workspace`
   *
   * An element that works with local storage to store ARC workspace data.
   */
  class ArcLocalStoreWorkspace extends Polymer.Element {

    /**
     * Storage preference key prefix
     */
    prefix: string|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;

    /**
     * Handler for the `workspace-state-read` custom event. Reads current
     * state of the ARC workspace.
     *
     * @param e Custom event
     */
    _readHandler(e: CustomEvent|null): void;

    /**
     * Handler for the `workspace-state-store` custom event. Saves current
     * state of the ARC workspace.
     */
    _changeHandler(e: CustomEvent|null): void;

    /**
     * Loads all stored workspace data
     *
     * @returns A promise resolved to the worspace data object
     */
    load(): Promise<any>|null;

    /**
     * Stores value in local store using `prefix` to construct the key.
     * The operation is debounced for 500 ms. Each call will clear the debouncer
     * and start over.
     *
     * @param value A value to store
     */
    store(value: any|null): void;
    _store(workspace: any): void;

    /**
     * Removes all stored workspace data.
     */
    clear(): void;

    /**
     * Creates a JSON wrapper for storage value. This ensures data types when
     * restorring values from local storage
     *
     * @param value Restored value
     * @returns Previously stored value.
     */
    _wrap(value: String|null): any|null;

    /**
     * Unwraps value from local storage data.
     *
     * @param value Read value
     * @returns originally stored value.
     */
    _unwrap(value: String|null): any|null;
  }
}

interface HTMLElementTagNameMap {
  "arc-local-store-workspace": LogicElements.ArcLocalStoreWorkspace;
}
